Roleslist command
alexcoder04/if-schleife-bot pull request #32
Opened 2022-07-26 21:23 UTC by alexcoder04

2022-07-26 21:32 UTC, CuzImClicks requested changes

2022-07-26 21:32 UTC, CuzImClicks commented on .gitignore
> -silenced.json
weil?

2022-07-26 21:32 UTC, CuzImClicks commented on src/commands/subscribe.js
> +            lg.info(`removed ${interaction.member.id} from ${role.name}`);
```suggestion
            lg.info(`Removed ${interaction.member.id} from ${role.name}`);
```
:)

2022-07-26 21:32 UTC, CuzImClicks commented on src/commands/subscribe.js
> +        lg.info(`added ${interaction.member.id} to ${role.name}`);
```suggestion
        lg.info(`Added ${interaction.member.id} to ${role.name}`);
```
:)

2022-07-26 21:40 UTC, alexcoder04 commented on .gitignore
> -silenced.json
#21

2022-07-26 21:42 UTC, alexcoder04 commented on src/commands/subscribe.js
> +            lg.info(`removed ${interaction.member.id} from ${role.name}`);
+

2022-07-29 14:31 UTC, CuzImClicks requested changes
Sieht sonst gut aus!

2022-07-29 14:31 UTC, CuzImClicks commented on src/commands/subscribe.js
> +
Mach das zu ner funktion mit arguments (role: String, interaction) -> boolean

2022-07-29 18:11 UTC, alexcoder04 commented on src/commands/subscribe.js
> +
Sorry, aber ich verstehe nicht ganz, was du meinst... Einfach die Argumente umzuändern macht ja keinen Sinn, meinst du in eine separate Funktion heraus refactorn?

2022-07-30 21:07 UTC, CuzImClicks commented on src/commands/subscribe.js
> +
Yepp

2022-07-31 10:47 UTC, alexcoder04 commented on src/commands/subscribe.js
> +
thx

2022-07-31 10:48 UTC, merged

2022-07-31 11:49 UTC, CuzImClicks commented
Ähhh ich meinte nur die permission function xD sry das war ein bisschen unklar formuliert! Sry! Kannst es jetzt so lassen wenn du möchtest oder es nochmal ändern

2022-07-31 11:50 UTC, CuzImClicks commented
Yk weil das permissions ding ist halt code den wir öfter verwenden werden... deswegen wollte ich den in eine andere function machen